export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const UPDATE_SORTERS = 'UPDATE_SORTERS';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const UPDATE_APPLIED_FILTERS = 'UPDATE_APPLIED_FILTERS';
